# Copyright 2026 Erik Lönroth
# See LICENSE file for licensing details.

"""Functions for managing and interacting with the workload.

The intention is that this module could be used outside the context of a charm.
"""

from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
import time
from pathlib import Path
from typing import Iterable

import yaml
import grp
import pwd

from config_builder import (
    DEFAULT_CONFIG_BACKUP_PATH,
    DEFAULT_CONFIG_PATH,
    DEFAULT_DATA_DIR,
    DEFAULT_PACKAGE_CONFIG_BACKUP_PATH,
)

logger = logging.getLogger(__name__)

GENERATED_CONFIG_HEADER = (
    "# This file is generated by Juju. Manual changes will be overwritten.\n"
    "# Adjust charm config to update this file.\n"
)
_GENERATED_HEADER_PREFIX = "# This file is generated by Juju."

GRAFANA_APT_SOURCE = (
    "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
)
GRAFANA_GPG_KEY_URL = "https://apt.grafana.com/gpg.key"

DEFAULT_VERIFY_TIMEOUT = 30
DEFAULT_START_TIMEOUT = 60


def _run(cmd: Iterable[str], *, timeout: int | None = None) -> subprocess.CompletedProcess[str]:
    """Run a command and return the completed process."""
    logger.debug("Running command: %s", " ".join(cmd))
    env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive"}
    return subprocess.run(
        list(cmd),
        check=True,
        text=True,
        capture_output=True,
        timeout=timeout,
        env=env,
    )


def _run_shell(cmd: str, *, timeout: int | None = None) -> subprocess.CompletedProcess[str]:
    """Run a shell command (used only for pipeline commands)."""
    logger.debug("Running shell command: %s", cmd)
    env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive"}
    return subprocess.run(
        cmd,
        check=True,
        text=True,
        capture_output=True,
        timeout=timeout,
        env=env,
        shell=True,
    )


def _systemctl(*args: str) -> None:
    """Run a systemctl command."""
    _run(["systemctl", *args])


def _wait_for_active(service: str, *, timeout: int = DEFAULT_START_TIMEOUT) -> None:
    """Wait for a systemd service to become active."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            _run(["systemctl", "is-active", "--quiet", service])
            return
        except subprocess.CalledProcessError:
            time.sleep(1)
    raise RuntimeError(f"Service {service} did not become active within {timeout} seconds")


# Functions for managing the workload process on the local machine:


def install() -> None:
    """Install the workload using the official Grafana APT repository."""
    _run(["apt-get", "update"])
    _run(["apt-get", "install", "-y", "wget", "gpg"])
    _run(["mkdir", "-p", "/etc/apt/keyrings"])
    _run_shell(
        f"wget -q -O - {GRAFANA_GPG_KEY_URL} | gpg --dearmor > /etc/apt/keyrings/grafana.gpg"
    )
    _run_shell(
        f'echo "{GRAFANA_APT_SOURCE}" | tee /etc/apt/sources.list.d/grafana.list'
    )
    _run(["apt-get", "update"])
    _run(["apt-get", "install", "-y", "loki"])


def ensure_data_dir(data_dir: str) -> None:
    """Ensure Loki data lives under the desired data directory.

    If a custom data directory is supplied, create a symlink from the default
    path to the custom path so the package defaults keep working.
    """
    default_path = Path(DEFAULT_DATA_DIR)

    if data_dir == DEFAULT_DATA_DIR:
        if default_path.is_symlink():
            default_path.unlink()
        elif default_path.exists() and not default_path.is_dir():
            default_path.unlink()
        default_path.mkdir(parents=True, exist_ok=True)
        _ensure_loki_permissions(default_path)
        return

    target = Path(data_dir)
    target.mkdir(parents=True, exist_ok=True)
    if default_path.is_symlink():
        if default_path.resolve() != target.resolve():
            default_path.unlink()
            default_path.symlink_to(target)
        _ensure_loki_permissions(target)
        return

    if default_path.exists():
        for item in default_path.iterdir():
            shutil.move(str(item), target / item.name)
        default_path.rmdir()
    else:
        default_path.parent.mkdir(parents=True, exist_ok=True)

    default_path.symlink_to(target)
    _ensure_loki_permissions(target)


def _ensure_loki_permissions(target: Path) -> None:
    """Ensure Loki can write to the data directories."""
    ids = _loki_ids()
    if ids is None:
        return
    uid, gid = ids
    _ensure_dir(target, uid, gid)
    _chown_tree(target, uid, gid)
    for subdir in (
        "chunks",
        "rules",
        "compactor",
        "tsdb-index",
        "tsdb-cache",
        "chunks/wal",
    ):
        _ensure_dir(target / subdir, uid, gid)


def _ensure_dir(path: Path, uid: int, gid: int) -> None:
    path.mkdir(parents=True, exist_ok=True)
    try:
        os.chown(path, uid, gid)
    except PermissionError:
        logger.debug("Skipping chown for %s (insufficient permissions)", path)


def _chown_tree(path: Path, uid: int, gid: int) -> None:
    """Recursively chown a directory tree, ignoring permission errors."""
    try:
        os.chown(path, uid, gid)
    except PermissionError:
        logger.debug("Skipping chown for %s (insufficient permissions)", path)
        return
    for root, dirs, files in os.walk(path):
        for name in dirs:
            try:
                os.chown(os.path.join(root, name), uid, gid)
            except PermissionError:
                logger.debug("Skipping chown for %s", os.path.join(root, name))
        for name in files:
            try:
                os.chown(os.path.join(root, name), uid, gid)
            except PermissionError:
                logger.debug("Skipping chown for %s", os.path.join(root, name))


def _loki_ids() -> tuple[int, int] | None:
    """Return (uid, gid) for loki user/group, or None if missing."""
    try:
        entry = pwd.getpwnam("loki")
        return entry.pw_uid, entry.pw_gid
    except KeyError:
        logger.warning("User/group 'loki' not found; skipping data dir ownership update.")
        return None


def ensure_data_dir_permissions(data_dir: str) -> None:
    """Ensure Loki can write to the data directory (root-only helper)."""
    if os.geteuid() != 0:
        return
    _ensure_loki_permissions(Path(data_dir))


def start() -> None:
    """Start the workload."""
    _systemctl("enable", "--now", "loki")
    _wait_for_active("loki")


def stop() -> None:
    """Stop the workload."""
    _systemctl("stop", "loki")


def restart() -> None:
    """Restart the workload."""
    _systemctl("restart", "loki")
    _wait_for_active("loki")


def reload() -> None:
    """Reload the workload."""
    _systemctl("reload", "loki")


# Functions for interacting with the workload, for example over HTTP:


def get_version() -> str | None:
    """Get the running version of the workload."""
    try:
        result = _run(["loki", "--version"])
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    output = f"{result.stdout}\n{result.stderr}".strip()
    match = re.search(r"version\s+([0-9]+(?:\.[0-9]+){1,3})", output)
    return match.group(1) if match else None


def write_config(
    config: dict,
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    backup_path: Path = Path(DEFAULT_CONFIG_BACKUP_PATH),
) -> None:
    """Write Loki configuration to disk and persist a backup copy."""
    config_yaml = yaml.safe_dump(config, sort_keys=False)
    _write_file_atomic(config_path, config_yaml)
    _write_file_atomic(backup_path, config_yaml)


def write_config_text(
    config_text: str,
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    backup_path: Path = Path(DEFAULT_CONFIG_BACKUP_PATH),
) -> None:
    """Write Loki configuration text to disk and persist a backup copy."""
    _write_file_atomic(config_path, config_text)
    _write_file_atomic(backup_path, config_text)


def preserve_default_config(
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    preserved_path: Path = Path(DEFAULT_PACKAGE_CONFIG_BACKUP_PATH),
) -> None:
    """Preserve the package default config file if it exists."""
    if not config_path.exists():
        return
    if _has_generated_header(config_path):
        logger.warning("Package default config already replaced by generated config.")
        return
    if preserved_path.exists():
        if _has_generated_header(preserved_path):
            shutil.copy2(config_path, preserved_path)
        return
    preserved_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(config_path, preserved_path)


def _has_generated_header(path: Path) -> bool:
    """Return True if the file starts with the Juju-generated header."""
    try:
        with path.open("r", encoding="utf-8") as handle:
            first_line = handle.readline().strip()
        return first_line.startswith(_GENERATED_HEADER_PREFIX)
    except OSError:
        return False


def verify_config(
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    timeout: int = DEFAULT_VERIFY_TIMEOUT,
) -> None:
    """Validate the Loki configuration using Loki's verify command."""
    _run(
        [
            "loki",
            "-config.file",
            str(config_path),
            "-verify-config",
        ],
        timeout=timeout,
    )


def _write_file_atomic(path: Path, content: str) -> None:
    """Write file atomically to avoid partial writes."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(f"{path.suffix}.tmp")
    tmp_path.write_text(content)
    tmp_path.replace(path)
